### PR TITLE
Changes for RN 0.72.6-1

### PR DESCRIPTION
**Pull request by douglowder**
@YatsynychRoman I made the following changes. This gets me to the loading screen with no errors. Please send any credentials I might need (client API key, etc.)

Changes:
- Expo CLI support
- Upgrade `react-native-gesture-handler` and patch (there were pod install errors before I did this)
- Fix metro config
- Upgrade `react-native-svg` and `react-native-svg-transformer`
- Add `tsconfig-path` to restore correct path behavior

### CODE REVIEW

**Comment by douglowder** [comment]
Got a bit farther and I'm now seeing redbox errors and working through them. Seems as though there is a problem with the usage of `VirtualizedList`.

**Comment by YatsynychRoman** [comment]
I've tried to change the `VirtualizedList` to `FlatList` and everything works fine until the next `VirtualizedList` occurs so the problem might be with the `VirtualizedList` itself

**Comment by douglowder** [comment]
@YatsynychRoman I don't yet have a solution for the `VirtualizedList` errors I'm seeing. I added notes in this PR description for the other changes I made, which I think you will want when moving to 0.72.

If necessary, I can provide a 0.71 patch specifically for the swipe issue on tvOS, so you can get that into production quickly and have more time for the 0.72 upgrade.

**Comment by YatsynychRoman** [comment]
It would be nice to have a patch for a 0.71, because this "swipes" issue is very crucial for us, so we want to fix it as soon as possible.

**Comment by douglowder** [comment]
@YatsynychRoman sounds good. I will create a PR for your repo that will remove unused gesture handlers in `react-native` and also in `react-native-gesture-handler`.

**Comment by douglowder** [comment]
ok @YatsynychRoman I got the app to work with 0.72.6-1, with a few additional changes.

- Improved patch for `react-native-gesture-handler`
- Upgrade Sentry packages
- The `VirtualizedList` errors were all coming from `RailSections`. I converted that to use `FlatList` and the app seems to work normally now.

Expo CLI seems to work fine, including support for Chrome dev tools debugging of Hermes.

**Comment by YatsynychRoman** [comment]
I will merge this into the `upgrade-react-native` branch and will check

**Comment by YatsynychRoman** [comment]
We are using `VirtualizedList` in different places and errors occurs in that places, so I might convert all of them to `FlatList`, everything else is looking good, thank you very much

**Comment by douglowder** [comment]
I am now working on fixing up Android TV...

**Pull request merged**
